# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.CharField(choices=[('cour-de-couture', 'Cour De Couture'), ('costumes-de-scenes', 'Costumes De Scenes'), ('creetion-sur-mesures', 'Creetion Sur Mesures'), ('atelier-de-creetion', 'Atelier De Creetion'), ('qui-suis-je', 'Ma presentation')], default='qui-suis-je', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='style',
            field=models.CharField(choices=[('primary', 'Style 1ere Importance'), ('secondary', 'Style secondaire'), ('default', 'Par defaut')], default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
