# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181021_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='texte',
        ),
    ]
